apiVersion: apps/v1
kind: Deployment
metadata:
  name: rndxdjango
spec: 
  selector:
    matchLabels:
      run: rndxdjango
  replicas: 2
  template:
    metadata:
      labels:
        run: rndxdjango
    spec: 
      containers:
      - name: rndxdjango
        image: <docker_image>
        ports: 
        - containerPort: 8000
